name: geoclap_test_final
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python==3.10.11
  - nginx==1.25.0
  - pip
  - pip:
    - pandas
    - geopy
    - cleantext
    - yacs
    - torch==1.13.1
    - torchvision
    - torchaudio
    - pytorch-lightning==2.0.2
    - transformers==4.28.1
    - timm==0.6.13
    - argparse
    - wandb
    - pyproj
    - mapproxy
    - avro
    - webdataset
    - pymap3d
    - lmdb
